import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { FiPlus } from "react-icons/fi";
import Button from "../../components/ui/Button";
import EmptyState from "../../components/common/EmptyState";
import Modal from "../../components/ui/Modal";
import { libraryService } from "../../services/libraryService";
import { apiError } from "../../services/api";

function LibraryForm({ library, done }) { const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: library || {} }); async function submit(values) { try { if (library) await libraryService.update(library.id, values); else await libraryService.create(values); toast.success(library ? "Library updated" : "Library created"); done(); } catch (error) { toast.error(apiError(error)); } } return <form onSubmit={handleSubmit(submit)} className="grid gap-4 sm:grid-cols-2">{[["name", "Library name"], ["city", "City"], ["address", "Address"], ["contact_email", "Contact email"], ["contact_phone", "Contact phone"]].map(([name, label]) => <label key={name} className="text-sm font-medium">{label}<input required={["name", "city", "address"].includes(name)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5" {...register(name)} /></label>)}<label className="sm:col-span-2 text-sm font-medium">Description<textarea className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5" rows="3" {...register("description")} /></label>{library && <label className="flex items-center gap-2 text-sm font-medium sm:col-span-2"><input type="checkbox" {...register("is_approved")} /> Approved and visible publicly</label>}<div className="sm:col-span-2"><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving…" : "Save library"}</Button></div></form>; }

function AdminLibraries() { const [items, setItems] = useState([]); const [editing, setEditing] = useState(undefined); function load() { libraryService.list({ approved_only: false, page_size: 100 }).then((data) => setItems(data.items)).catch((error) => toast.error(apiError(error))); } useEffect(load, []); async function remove(item) { if (!window.confirm(`Delete “${item.name}”?`)) return; try { await libraryService.remove(item.id); toast.success("Library deleted"); load(); } catch (error) { toast.error(apiError(error)); } } function done() { setEditing(undefined); load(); } return <section><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">Libraries</h2><p className="mt-1 text-slate-600">Review, approve, and maintain participating libraries.</p></div><Button onClick={() => setEditing(null)}><FiPlus className="mr-2" />Add library</Button></div><div className="mt-7 grid gap-4">{items.length ? items.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div><h3 className="font-bold">{item.name}</h3><p className="mt-1 text-sm text-slate-500">{item.city} · {item.contact_email || "No email"}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.is_approved ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{item.is_approved ? "Approved" : "Pending"}</span><Button variant="secondary" className="px-3 py-2 text-sm" onClick={() => setEditing(item)}>Edit</Button><Button variant="danger" className="px-3 py-2 text-sm" onClick={() => remove(item)}>Delete</Button></div></article>) : <EmptyState title="No libraries found" />}</div>{editing !== undefined && <Modal title={editing ? "Edit library" : "Add library"} onClose={() => setEditing(undefined)}><LibraryForm library={editing} done={done} /></Modal>}</section>; }

export default AdminLibraries;
