import { useEffect, useState } from "react";
import { FiSearch, FiSliders } from "react-icons/fi";
import BookCard from "../../../components/books/BookCard";
import EmptyState from "../../../components/common/EmptyState";
import Pagination from "../../../components/common/Pagination";
import { bookService } from "../../../services/bookService";
import { apiError } from "../../../services/api";

function Books() {
  const [result, setResult] = useState({ items: [], pages: 0, page: 1 }); const [filters, setFilters] = useState({ categories: [], languages: [] }); const [query, setQuery] = useState(""); const [params, setParams] = useState({ page: 1, category: "", language: "", availability: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { bookService.filters().then(setFilters).catch(() => {}); }, []);
  useEffect(() => { let active = true; setLoading(true); setError(""); const timer = setTimeout(() => { bookService.list({ ...params, q: query || undefined, category: params.category || undefined, language: params.language || undefined, availability: params.availability || undefined }).then((data) => active && setResult(data)).catch((requestError) => active && setError(apiError(requestError))).finally(() => active && setLoading(false)); }, 250); return () => { active = false; clearTimeout(timer); }; }, [params, query]);
  function updateFilter(name, value) { setParams((current) => ({ ...current, [name]: value, page: 1 })); }
  return <section className="mx-auto max-w-7xl px-6 py-14"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Library catalogue</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-900">Find your next great read</h1><p className="mt-3 text-slate-600">Explore books across LibConnect libraries, then borrow or reserve them from the details page.</p></div><div className="mt-9 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_auto_auto_auto]"><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3"><FiSearch className="text-slate-400" /><input aria-label="Search books" className="w-full py-3 outline-none" placeholder="Title, author, ISBN or subject" value={query} onChange={(event) => { setQuery(event.target.value); setParams((current) => ({ ...current, page: 1 })); }} /></label><label className="sr-only" htmlFor="category">Category</label><select id="category" className="rounded-xl border border-slate-200 px-3 py-3 text-sm" value={params.category} onChange={(event) => updateFilter("category", event.target.value)}><option value="">All categories</option>{filters.categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-3 text-sm" value={params.language} onChange={(event) => updateFilter("language", event.target.value)}><option value="">All languages</option>{filters.languages.map((item) => <option key={item} value={item}>{item}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-3 text-sm" value={params.availability} onChange={(event) => updateFilter("availability", event.target.value)}><option value="">Any availability</option><option value="available">Available now</option><option value="unavailable">On loan</option></select></div><div className="mt-8 flex items-center justify-between"><p className="text-sm text-slate-500">{result.total ?? 0} books found</p><span className="flex items-center gap-2 text-sm text-slate-500"><FiSliders /> Refine your search</span></div>{error ? <div className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</div> : loading ? <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div key={index} className="h-80 animate-pulse rounded-2xl bg-slate-200" />)}</div> : result.items.length ? <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{result.items.map((book) => <BookCard key={book.id} book={book} />)}</div> : <div className="mt-6"><EmptyState title="No books match that search" description="Try a different title, author, or filter." /></div>}<Pagination page={result.page} pages={result.pages} onPageChange={(page) => setParams((current) => ({ ...current, page }))} /></section>;
}

export default Books;
