export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  BOOKS: "/books",
  CONTACT: "/contact",

  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  LIBRARIES: "/libraries",
  LIBRARY_REGISTER: "/libraries/register",
  FAQ: "/faq",
  STUDENT: "/student",
  STUDENT_BORROWS: "/student/borrows",
  STUDENT_RESERVATIONS: "/student/reservations",
  STUDENT_NOTIFICATIONS: "/student/notifications",
  PROFILE: "/profile",
  LIBRARIAN: "/librarian",
  LIBRARIAN_BOOKS: "/librarian/books",
  LIBRARIAN_REQUESTS: "/librarian/requests",
  LIBRARIAN_BORROWED: "/librarian/borrowed",
  LIBRARIAN_RESERVATIONS: "/librarian/reservations",
  LIBRARIAN_NOTIFICATIONS: "/librarian/notifications",
  ADMIN: "/admin",
  ADMIN_LIBRARIES: "/admin/libraries",
  ADMIN_USERS: "/admin/users",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
};
